/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { TournamentScores } from './TournamentScores.js';
export * as factories from './factories/index.js';
export { TournamentScores__factory } from './factories/TournamentScores__factory.js';