/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface TournamentScoresInterface extends Interface {
    getFunction(nameOrSignature: "finalizeTournament" | "getTournament" | "owner"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "TournamentFinalized"): EventFragment;

    encodeFunctionData(functionFragment: 'finalizeTournament', values: [string, string, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'getTournament', values: [string]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'finalizeTournament', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTournament', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
  }

  
    export namespace TournamentFinalizedEvent {
      export type InputTuple = [tournamentKey: BytesLike, tournamentId: string, winnerAlias: string, scoreLeft: BigNumberish, scoreRight: BigNumberish, finalizedAt: BigNumberish];
      export type OutputTuple = [tournamentKey: string, tournamentId: string, winnerAlias: string, scoreLeft: bigint, scoreRight: bigint, finalizedAt: bigint];
      export interface OutputObject {tournamentKey: string, tournamentId: string, winnerAlias: string, scoreLeft: bigint, scoreRight: bigint, finalizedAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TournamentScores extends BaseContract {
    
    connect(runner?: ContractRunner | null): TournamentScores;
    waitForDeployment(): Promise<this>;

    interface: TournamentScoresInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    finalizeTournament: TypedContractMethod<
      [tournamentId: string, winnerAlias: string, scoreLeft: BigNumberish, scoreRight: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getTournament: TypedContractMethod<
      [tournamentId: string, ],
      [[boolean, bigint, string, bigint, bigint] & {exists: boolean, finalizedAt: bigint, winnerAlias: string, scoreLeft: bigint, scoreRight: bigint }],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'finalizeTournament'): TypedContractMethod<
      [tournamentId: string, winnerAlias: string, scoreLeft: BigNumberish, scoreRight: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTournament'): TypedContractMethod<
      [tournamentId: string, ],
      [[boolean, bigint, string, bigint, bigint] & {exists: boolean, finalizedAt: bigint, winnerAlias: string, scoreLeft: bigint, scoreRight: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'TournamentFinalized'): TypedContractEvent<TournamentFinalizedEvent.InputTuple, TournamentFinalizedEvent.OutputTuple, TournamentFinalizedEvent.OutputObject>;

    filters: {
      
      'TournamentFinalized(bytes32,string,string,uint16,uint16,uint256)': TypedContractEvent<TournamentFinalizedEvent.InputTuple, TournamentFinalizedEvent.OutputTuple, TournamentFinalizedEvent.OutputObject>;
      TournamentFinalized: TypedContractEvent<TournamentFinalizedEvent.InputTuple, TournamentFinalizedEvent.OutputTuple, TournamentFinalizedEvent.OutputObject>;
    
    };
  }